name: joint-multilingual-analysis
channels:
  - pytorch
dependencies:
  - pip
  - python=3.10.12
  - pyyaml
  - readline
  - requests
  - setuptools
  - wheel
  - pip:
    - numpy
    - conllu==4.5.2
    - matplotlib==3.5.1
    - pandas
    - pykakasi==2.2.1
    - pypinyin==0.48.0
    - seaborn==0.12.2
    - sentencepiece==0.1.96
    - statsmodels==0.13.5
    - tensorly==0.7.0
    - tokenizers==0.11.5
    - torch==1.12.1
    - torchmetrics==0.5.0
    - tqdm==4.62.1
    - transformers==4.24.0
    - torch-scatter==2.0.9
    - termcolor

